File "bench/check-ce/log-call-nc.mlw", line 14, characters 12-21:
Sub-goal Postcondition of goal f'vc.
Prover result is: Valid (6 steps).

File "bench/check-ce/log-call-nc.mlw", line 19, characters 2-5:
Sub-goal Precondition of goal f1'vc.
Prover result is: Valid (2 steps).

<check_ce:categorization>Categorizations of models:
- Selected model 0: NC
  - Concrete RAC: FAILURE (assertion at "bench/check-ce/log-call-nc.mlw", line 20, characters 11-16)
  - Abstract RAC: STUCK (failure in postcondition of `f` at "bench/check-ce/log-call-nc.mlw", line 14, characters 12-21)
- Checked model 1: NC
  - Concrete RAC: FAILURE (assertion at "bench/check-ce/log-call-nc.mlw", line 20, characters 11-16)
  - Abstract RAC: FAILURE (assertion at "bench/check-ce/log-call-nc.mlw", line 20, characters 11-16)
- Checked model 2: NC
  - Concrete RAC: FAILURE (assertion at "bench/check-ce/log-call-nc.mlw", line 20, characters 11-16)
  - Abstract RAC: FAILURE (assertion at "bench/check-ce/log-call-nc.mlw", line 20, characters 11-16)
File "bench/check-ce/log-call-nc.mlw", line 20, characters 11-16:
Sub-goal Assertion of goal f1'vc.
Prover result is: Unknown (unknown) (7 steps).
The program does not comply to the verification goal, for example during the
  following execution:
File int.mlw:
  Line 13:
    Constant zero initialization
    zero = 0
  Line 14:
    Constant one initialization
    one = 1
File log-call-nc.mlw:
  Line 9:
    Constant x initialization
    (giant-step) execution of unimplemented function with args:
    result = 0
    Normal execution of function `ref` with args:
      contents = 0
    Normal execution of function `ref'mk` with args:
      contents = 0
    x = {contents= 0}
Unknown location:
    _ = ()
File log-call-nc.mlw:
  Line 17:
    _ = ()
    Execution of main function `f1` with env:
      x = {contents= 0}
      _ = ()
      zero = 0
      one = 1
  Line 19:
    Normal execution of function `f` with args:
      y = 1
  Line 15:
    Normal execution of function `contents` with args:
      arg = {contents= 0}
    Normal execution of function `(+)` with args:
      _ = 0
      _ = 1
  Line 20:
    Property failure at assertion with:
      x = {contents= 1}

