
exception Exception int

use import ref.Ref

val t : ref int

val m (a:int) (b:int) : unit raises { Exception }

let test () raises { Exception } = (m ( assert { true } ; 0) 0)

