module Try
  use import int.Int
  use import ref.Ref

  exception Test

(* Valid *)
  let test1 (x : ref int) =
    {}
    try raise Test
    with Test -> x := !x + 1
    end
    { !x = old !x + 1 }

(* Unknown *)
  let test2 (x : ref int) =
    {}
    try raise Test
    with Test -> x := !x + 1
    end
    { !x = old !x }

(* Valid *)
  let test3 (x : ref int) =
    {}
    try
      if !x > 0 then raise Test;
      x := !x + 1
    with Test -> x := !x + 2
    end
    { if old !x > 0 then !x = old !x + 2 else !x = old !x + 1 }

(* Unknown *)
  let test4 (x : ref int) =
    {}
    try
      if !x > 0 then raise Test;
      x := !x + 1
    with Test -> x := !x + 2
    end
    { if old !x > 0 then !x = old !x + 1 else !x = old !x + 2 }
end

